INSERT INTO role (name) SELECT 'ADMIN' WHERE NOT EXISTS (SELECT 1 from role WHERE name = 'ADMIN');
INSERT INTO role (name) SELECT 'LENDER' WHERE NOT EXISTS (SELECT 1 from role WHERE name = 'LENDER');
INSERT INTO role (name) SELECT 'BORROWER' WHERE NOT EXISTS (SELECT 1 from role WHERE name = 'BORROWER');